import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
    return (
        <>
            <Head>
                <title>n-News</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <style>
                {`
                    a{
                        display: 'inline-block';
                        color: lime;
                        margin: 10px 20px;
                        font-weight: bolder;
                    }
                `}
            </style>

            <main>
                <div>
                    <Link href={`/`}>
                        <a>Home</a>
                    </Link>

                    <Link href={`/user`}>
                        <a>user</a>
                    </Link>

                    <Link href={`/post`}>
                        <a>post</a>
                    </Link>
                </div>
            </main>
        </>
    )
}
